version: "3.9"
services:
  postgres:
    image: postgres:16-alpine
    container_name: expense-postgres
    environment:
      POSTGRES_DB: expense_manager
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - expense_pg_data:/var/lib/postgresql/data

volumes:
  expense_pg_data:
